# Generated by Django 5.0.4 on 2024-04-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_user_security_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='security_question',
        ),
    ]
