# Generated by Django 5.0.4 on 2024-04-10 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='package',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='package',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pictures',
        ),
        migrations.AddField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(to='management.activity'),
        ),
        migrations.AddField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(to='management.flight'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(to='management.hotel'),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('registrationid', models.CharField(max_length=100)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.agency'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
