# Generated by Django 5.0.4 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_custompackage_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='activities',
            field=models.ManyToManyField(blank=True, to='management.activity'),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='flights',
            field=models.ManyToManyField(blank=True, to='management.flight'),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='management.hotel'),
        ),
    ]
