# Generated by Django 5.0.4 on 2024-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_activity_pictures_alter_flight_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(blank=True, to='management.activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(blank=True, to='management.flight'),
        ),
        migrations.AlterField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='management.hotel'),
        ),
    ]
