# Generated by Django 5.0.4 on 2024-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_custompackage_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
