# Generated by Django 5.0.4 on 2024-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='f_des',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='f_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
